apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: postgres_db:5432
    database: test_db
    user: user
    secureJsonData:
      password: pass
    jsonData:
      sslmode: 'disable'
      postgresVersion: 15
      timescaledb: false
    isDefault: true
    editable: true